// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

// CreateZipJobResponseBody - A generic error returned by the API
type CreateZipJobResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (c *CreateZipJobResponseBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CreateZipJobResponseBody) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

type CreateZipJobResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Job created, processing in background
	ZipJob *shared.ZipJob
	// Invalid request parameters or payload
	Object *CreateZipJobResponseBody
}

func (c *CreateZipJobResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateZipJobResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateZipJobResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateZipJobResponse) GetZipJob() *shared.ZipJob {
	if c == nil {
		return nil
	}
	return c.ZipJob
}

func (c *CreateZipJobResponse) GetObject() *CreateZipJobResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
