// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type CreateFileSummaryJobRequest struct {
	// The UUID of the file entity
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (c *CreateFileSummaryJobRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

// CreateFileSummaryJobResponseBody - A generic error returned by the API
type CreateFileSummaryJobResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (c *CreateFileSummaryJobResponseBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CreateFileSummaryJobResponseBody) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

type CreateFileSummaryJobResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Summary job accepted
	FileSummaryJob *shared.FileSummaryJob
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *CreateFileSummaryJobResponseBody
}

func (c *CreateFileSummaryJobResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateFileSummaryJobResponse) GetFileSummaryJob() *shared.FileSummaryJob {
	if c == nil {
		return nil
	}
	return c.FileSummaryJob
}

func (c *CreateFileSummaryJobResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateFileSummaryJobResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateFileSummaryJobResponse) GetObject() *CreateFileSummaryJobResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
