// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type CreateUserSchemaFileCollectionRequest struct {
	FileCollectionCreateRequest shared.FileCollectionCreateRequest `request:"mediaType=application/json"`
	// The entity schema slug (e.g., order, opportunity, contact)
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (c *CreateUserSchemaFileCollectionRequest) GetFileCollectionCreateRequest() shared.FileCollectionCreateRequest {
	if c == nil {
		return shared.FileCollectionCreateRequest{}
	}
	return c.FileCollectionCreateRequest
}

func (c *CreateUserSchemaFileCollectionRequest) GetSlug() string {
	if c == nil {
		return ""
	}
	return c.Slug
}

// CreateUserSchemaFileCollectionResponseBody - A generic error returned by the API
type CreateUserSchemaFileCollectionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (c *CreateUserSchemaFileCollectionResponseBody) GetError() *string {
	if c == nil {
		return nil
	}
	return c.Error
}

func (c *CreateUserSchemaFileCollectionResponseBody) GetStatus() *int64 {
	if c == nil {
		return nil
	}
	return c.Status
}

type CreateUserSchemaFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File collection created successfully
	FileCollectionItem *shared.FileCollectionItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *CreateUserSchemaFileCollectionResponseBody
}

func (c *CreateUserSchemaFileCollectionResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateUserSchemaFileCollectionResponse) GetFileCollectionItem() *shared.FileCollectionItem {
	if c == nil {
		return nil
	}
	return c.FileCollectionItem
}

func (c *CreateUserSchemaFileCollectionResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateUserSchemaFileCollectionResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateUserSchemaFileCollectionResponse) GetObject() *CreateUserSchemaFileCollectionResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
