// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type CreateUserSchemaFileCollectionRequest struct {
	FileCollectionCreateRequest shared.FileCollectionCreateRequest `request:"mediaType=application/json"`
	// The schema slug (e.g., order, opportunity)
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *CreateUserSchemaFileCollectionRequest) GetFileCollectionCreateRequest() shared.FileCollectionCreateRequest {
	if o == nil {
		return shared.FileCollectionCreateRequest{}
	}
	return o.FileCollectionCreateRequest
}

func (o *CreateUserSchemaFileCollectionRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type CreateUserSchemaFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File collection created successfully
	FileCollectionItem *shared.FileCollectionItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateUserSchemaFileCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateUserSchemaFileCollectionResponse) GetFileCollectionItem() *shared.FileCollectionItem {
	if o == nil {
		return nil
	}
	return o.FileCollectionItem
}

func (o *CreateUserSchemaFileCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateUserSchemaFileCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
