// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteUserSchemaFileCollectionRequest struct {
	// The slug identifier for the collection
	CollectionSlug string `pathParam:"style=simple,explode=false,name=collectionSlug"`
	// The schema slug (e.g., order, opportunity)
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *DeleteUserSchemaFileCollectionRequest) GetCollectionSlug() string {
	if o == nil {
		return ""
	}
	return o.CollectionSlug
}

func (o *DeleteUserSchemaFileCollectionRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// DeleteUserSchemaFileCollectionResponseBody - A generic error returned by the API
type DeleteUserSchemaFileCollectionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *DeleteUserSchemaFileCollectionResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteUserSchemaFileCollectionResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteUserSchemaFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *DeleteUserSchemaFileCollectionResponseBody
}

func (o *DeleteUserSchemaFileCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteUserSchemaFileCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteUserSchemaFileCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteUserSchemaFileCollectionResponse) GetObject() *DeleteUserSchemaFileCollectionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
