// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteFileFolderRequest struct {
	// The slug identifier for the folder
	FolderSlug string `pathParam:"style=simple,explode=false,name=folderSlug"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteFileFolderRequest) GetFolderSlug() string {
	if o == nil {
		return ""
	}
	return o.FolderSlug
}

func (o *DeleteFileFolderRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteFileFolderResponseBody - A generic error returned by the API
type DeleteFileFolderResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *DeleteFileFolderResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteFileFolderResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteFileFolderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *DeleteFileFolderResponseBody
}

func (o *DeleteFileFolderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFileFolderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFileFolderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFileFolderResponse) GetObject() *DeleteFileFolderResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
