// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteFileCollectionRequest struct {
	// The slug identifier for the collection
	CollectionSlug string `pathParam:"style=simple,explode=false,name=collectionSlug"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteFileCollectionRequest) GetCollectionSlug() string {
	if o == nil {
		return ""
	}
	return o.CollectionSlug
}

func (o *DeleteFileCollectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// DeleteFileCollectionResponseBody - A generic error returned by the API
type DeleteFileCollectionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *DeleteFileCollectionResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *DeleteFileCollectionResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *DeleteFileCollectionResponseBody
}

func (o *DeleteFileCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteFileCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteFileCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteFileCollectionResponse) GetObject() *DeleteFileCollectionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
