// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type DeleteFileRequest struct {
	// Activity to include in event feed
	ActivityID *string `queryParam:"style=form,explode=true,name=activity_id"`
	ID         string  `pathParam:"style=simple,explode=false,name=id"`
	Purge      *bool   `default:"false" queryParam:"style=form,explode=true,name=purge"`
	// When passed true, the response will contain only fields that match the schema, with non-matching fields included in `__additional`
	Strict *bool `default:"false" queryParam:"style=form,explode=true,name=strict"`
}

func (d DeleteFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (d *DeleteFileRequest) GetActivityID() *string {
	if d == nil {
		return nil
	}
	return d.ActivityID
}

func (d *DeleteFileRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *DeleteFileRequest) GetPurge() *bool {
	if d == nil {
		return nil
	}
	return d.Purge
}

func (d *DeleteFileRequest) GetStrict() *bool {
	if d == nil {
		return nil
	}
	return d.Strict
}

type DeleteFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// The deleted file
	FileEntity *shared.FileEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteFileResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteFileResponse) GetFileEntity() *shared.FileEntity {
	if d == nil {
		return nil
	}
	return d.FileEntity
}

func (d *DeleteFileResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteFileResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
