// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"net/http"
)

type DownloadS3FileRequest struct {
	// Controls the Content-Disposition header. Set to `true` to trigger browser download dialog, `false` to display inline.
	Attachment *bool `default:"true" queryParam:"style=form,explode=true,name=attachment"`
	// The S3 bucket name
	S3Bucket string `queryParam:"style=form,explode=true,name=s3_bucket"`
	// The S3 object key
	S3Key string `queryParam:"style=form,explode=true,name=s3_key"`
}

func (d DownloadS3FileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DownloadS3FileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DownloadS3FileRequest) GetAttachment() *bool {
	if d == nil {
		return nil
	}
	return d.Attachment
}

func (d *DownloadS3FileRequest) GetS3Bucket() string {
	if d == nil {
		return ""
	}
	return d.S3Bucket
}

func (d *DownloadS3FileRequest) GetS3Key() string {
	if d == nil {
		return ""
	}
	return d.S3Key
}

// #region class-body-downloads3filerequest
// #endregion class-body-downloads3filerequest

// DownloadS3FileFileResponseBody - A generic error returned by the API
type DownloadS3FileFileResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (d *DownloadS3FileFileResponseBody) GetError() *string {
	if d == nil {
		return nil
	}
	return d.Error
}

func (d *DownloadS3FileFileResponseBody) GetStatus() *int64 {
	if d == nil {
		return nil
	}
	return d.Status
}

// #region class-body-downloads3filefileresponsebody
// #endregion class-body-downloads3filefileresponsebody

// DownloadS3FileResponseBody - Pre-signed download URL
type DownloadS3FileResponseBody struct {
	// Pre-signed S3 URL valid for downloading the file
	DownloadURL *string `json:"download_url,omitempty"`
}

func (d *DownloadS3FileResponseBody) GetDownloadURL() *string {
	if d == nil {
		return nil
	}
	return d.DownloadURL
}

// #region class-body-downloads3fileresponsebody
// #endregion class-body-downloads3fileresponsebody

type DownloadS3FileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Pre-signed download URL
	Object *DownloadS3FileResponseBody
	// Invalid request parameters or payload
	Object1 *DownloadS3FileFileResponseBody
}

func (d *DownloadS3FileResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DownloadS3FileResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DownloadS3FileResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DownloadS3FileResponse) GetObject() *DownloadS3FileResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}

func (d *DownloadS3FileResponse) GetObject1() *DownloadS3FileFileResponseBody {
	if d == nil {
		return nil
	}
	return d.Object1
}

// #region class-body-downloads3fileresponse
// #endregion class-body-downloads3fileresponse
