// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ResponseBody struct {
	DownloadURL  *string `json:"download_url,omitempty"`
	FileEntityID *string `json:"file_entity_id,omitempty"`
}

func (r *ResponseBody) GetDownloadURL() *string {
	if r == nil {
		return nil
	}
	return r.DownloadURL
}

func (r *ResponseBody) GetFileEntityID() *string {
	if r == nil {
		return nil
	}
	return r.FileEntityID
}

type DownloadFilesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Generated download urls
	Classes []ResponseBody
}

func (d *DownloadFilesResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DownloadFilesResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DownloadFilesResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DownloadFilesResponse) GetClasses() []ResponseBody {
	if d == nil {
		return nil
	}
	return d.Classes
}
