// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GeneratePublicLinkRequest struct {
	// The UUID of the file entity to share
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GeneratePublicLinkRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GeneratePublicLinkResponseBody - A generic error returned by the API
type GeneratePublicLinkResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GeneratePublicLinkResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GeneratePublicLinkResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GeneratePublicLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authentication required or invalid credentials
	Object *GeneratePublicLinkResponseBody
	// Public link generated successfully
	String *string
}

func (g *GeneratePublicLinkResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GeneratePublicLinkResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GeneratePublicLinkResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GeneratePublicLinkResponse) GetObject() *GeneratePublicLinkResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GeneratePublicLinkResponse) GetString() *string {
	if g == nil {
		return nil
	}
	return g.String
}
