// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetFilesInFolderRequest struct {
	// The slug identifier for the folder
	FolderSlug string `pathParam:"style=simple,explode=false,name=folderSlug"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetFilesInFolderRequest) GetFolderSlug() string {
	if o == nil {
		return ""
	}
	return o.FolderSlug
}

func (o *GetFilesInFolderRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetFilesInFolderFileFoldersResponseBody - Entity or folder not found
type GetFilesInFolderFileFoldersResponseBody struct {
	Error *string `json:"error,omitempty"`
}

func (o *GetFilesInFolderFileFoldersResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

// GetFilesInFolderResponseBody - User must have permission to view this entity to access its files
type GetFilesInFolderResponseBody struct {
	Error *string `json:"error,omitempty"`
}

func (o *GetFilesInFolderResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type GetFilesInFolderResponse struct {
	// List of files in the folder
	TwoHundredApplicationJSONClasses []shared.FileEntity
	// User must have permission to view this entity to access its files
	FourHundredAndThreeApplicationJSONObject *GetFilesInFolderResponseBody
	// Entity or folder not found
	FourHundredAndFourApplicationJSONObject *GetFilesInFolderFileFoldersResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetFilesInFolderResponse) GetTwoHundredApplicationJSONClasses() []shared.FileEntity {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONClasses
}

func (o *GetFilesInFolderResponse) GetFourHundredAndThreeApplicationJSONObject() *GetFilesInFolderResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *GetFilesInFolderResponse) GetFourHundredAndFourApplicationJSONObject() *GetFilesInFolderFileFoldersResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *GetFilesInFolderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFilesInFolderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFilesInFolderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
