// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetFileSummaryRequest struct {
	// The UUID of the file entity
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetFileSummaryRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

// GetFileSummaryResponseBody - A generic error returned by the API
type GetFileSummaryResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetFileSummaryResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetFileSummaryResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetFileSummaryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Current file summary state
	FileSummary *shared.FileSummary
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *GetFileSummaryResponseBody
}

func (g *GetFileSummaryResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFileSummaryResponse) GetFileSummary() *shared.FileSummary {
	if g == nil {
		return nil
	}
	return g.FileSummary
}

func (g *GetFileSummaryResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFileSummaryResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetFileSummaryResponse) GetObject() *GetFileSummaryResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
