// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetFilesInCollectionRequest struct {
	// The slug identifier for the collection
	CollectionSlug string `pathParam:"style=simple,explode=false,name=collectionSlug"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetFilesInCollectionRequest) GetCollectionSlug() string {
	if o == nil {
		return ""
	}
	return o.CollectionSlug
}

func (o *GetFilesInCollectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// GetFilesInCollectionFileCollectionsResponseBody - Entity or collection not found
type GetFilesInCollectionFileCollectionsResponseBody struct {
	Error *string `json:"error,omitempty"`
}

func (o *GetFilesInCollectionFileCollectionsResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

// GetFilesInCollectionResponseBody - User must have permission to view this entity to access its files
type GetFilesInCollectionResponseBody struct {
	Error *string `json:"error,omitempty"`
}

func (o *GetFilesInCollectionResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

type GetFilesInCollectionResponse struct {
	// List of files in the collection
	TwoHundredApplicationJSONClasses []shared.FileEntity
	// User must have permission to view this entity to access its files
	FourHundredAndThreeApplicationJSONObject *GetFilesInCollectionResponseBody
	// Entity or collection not found
	FourHundredAndFourApplicationJSONObject *GetFilesInCollectionFileCollectionsResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetFilesInCollectionResponse) GetTwoHundredApplicationJSONClasses() []shared.FileEntity {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONClasses
}

func (o *GetFilesInCollectionResponse) GetFourHundredAndThreeApplicationJSONObject() *GetFilesInCollectionResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *GetFilesInCollectionResponse) GetFourHundredAndFourApplicationJSONObject() *GetFilesInCollectionFileCollectionsResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *GetFilesInCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFilesInCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFilesInCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
