// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetFileRequest struct {
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async     *bool  `default:"false" queryParam:"style=form,explode=true,name=async"`
	ID        string `pathParam:"style=simple,explode=false,name=id"`
	SourceURL *bool  `default:"false" queryParam:"style=form,explode=true,name=source_url"`
	// When passed true, the response will contain only fields that match the schema, with non-matching fields included in `__additional`
	Strict *bool `default:"false" queryParam:"style=form,explode=true,name=strict"`
}

func (g GetFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (g *GetFileRequest) GetAsync() *bool {
	if g == nil {
		return nil
	}
	return g.Async
}

func (g *GetFileRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetFileRequest) GetSourceURL() *bool {
	if g == nil {
		return nil
	}
	return g.SourceURL
}

func (g *GetFileRequest) GetStrict() *bool {
	if g == nil {
		return nil
	}
	return g.Strict
}

type GetFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File Entity
	FileEntity *shared.FileEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetFileResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetFileResponse) GetFileEntity() *shared.FileEntity {
	if g == nil {
		return nil
	}
	return g.FileEntity
}

func (g *GetFileResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetFileResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}
