// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetGlobalFileFoldersRequest struct {
	// The schema slug (e.g., order, opportunity)
	SchemaSlug string `pathParam:"style=simple,explode=false,name=schemaSlug"`
}

func (g *GetGlobalFileFoldersRequest) GetSchemaSlug() string {
	if g == nil {
		return ""
	}
	return g.SchemaSlug
}

type GetGlobalFileFoldersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of global folders for the schema
	Classes []shared.FileFolderItem
}

func (g *GetGlobalFileFoldersResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGlobalFileFoldersResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGlobalFileFoldersResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetGlobalFileFoldersResponse) GetClasses() []shared.FileFolderItem {
	if g == nil {
		return nil
	}
	return g.Classes
}
