// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetGlobalFileCollectionsRequest struct {
	// The entity schema slug (e.g., order, opportunity, contact)
	SchemaSlug string `pathParam:"style=simple,explode=false,name=schemaSlug"`
}

func (g *GetGlobalFileCollectionsRequest) GetSchemaSlug() string {
	if g == nil {
		return ""
	}
	return g.SchemaSlug
}

// GetGlobalFileCollectionsResponseBody - A generic error returned by the API
type GetGlobalFileCollectionsResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetGlobalFileCollectionsResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetGlobalFileCollectionsResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetGlobalFileCollectionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of global collections for the schema
	Classes []shared.FileCollectionItem
	// Authentication required or invalid credentials
	Object *GetGlobalFileCollectionsResponseBody
}

func (g *GetGlobalFileCollectionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetGlobalFileCollectionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetGlobalFileCollectionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetGlobalFileCollectionsResponse) GetClasses() []shared.FileCollectionItem {
	if g == nil {
		return nil
	}
	return g.Classes
}

func (g *GetGlobalFileCollectionsResponse) GetObject() *GetGlobalFileCollectionsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
