// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetUserSchemaFileCollectionsRequest struct {
	// The schema slug (e.g., order, opportunity)
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (g *GetUserSchemaFileCollectionsRequest) GetSlug() string {
	if g == nil {
		return ""
	}
	return g.Slug
}

type GetUserSchemaFileCollectionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of collections for the user and schema
	Classes []shared.FileCollectionItem
}

func (g *GetUserSchemaFileCollectionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUserSchemaFileCollectionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUserSchemaFileCollectionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUserSchemaFileCollectionsResponse) GetClasses() []shared.FileCollectionItem {
	if g == nil {
		return nil
	}
	return g.Classes
}
