// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type GetZipJobRequest struct {
	// The UUID of the ZIP job
	JobID string `pathParam:"style=simple,explode=false,name=job_id"`
}

func (g *GetZipJobRequest) GetJobID() string {
	if g == nil {
		return ""
	}
	return g.JobID
}

// GetZipJobResponseBody - A generic error returned by the API
type GetZipJobResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (g *GetZipJobResponseBody) GetError() *string {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetZipJobResponseBody) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetZipJobResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// ZIP job status
	ZipJob *shared.ZipJob
	// Authentication required or invalid credentials
	Object *GetZipJobResponseBody
}

func (g *GetZipJobResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetZipJobResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetZipJobResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetZipJobResponse) GetZipJob() *shared.ZipJob {
	if g == nil {
		return nil
	}
	return g.ZipJob
}

func (g *GetZipJobResponse) GetObject() *GetZipJobResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
