// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"net/http"
)

type PreviewFileRequest struct {
	// Desired height in pixels (maintains aspect ratio if only height is specified)
	H *int64 `queryParam:"style=form,explode=true,name=h"`
	// The UUID of the file entity
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Index of the file version to preview (0 = latest)
	Version *int64 `default:"0" queryParam:"style=form,explode=true,name=version"`
	// Desired width in pixels (maintains aspect ratio if only width is specified)
	W *int64 `queryParam:"style=form,explode=true,name=w"`
}

func (p PreviewFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PreviewFileRequest) GetH() *int64 {
	if p == nil {
		return nil
	}
	return p.H
}

func (p *PreviewFileRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PreviewFileRequest) GetVersion() *int64 {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PreviewFileRequest) GetW() *int64 {
	if p == nil {
		return nil
	}
	return p.W
}

// PreviewFileResponseBody - A generic error returned by the API
type PreviewFileResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (p *PreviewFileResponseBody) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PreviewFileResponseBody) GetStatus() *int64 {
	if p == nil {
		return nil
	}
	return p.Status
}

type PreviewFileResponse struct {
	// Generated thumbnail image
	TwoHundredImageJpegBytes []byte
	// Generated thumbnail image
	TwoHundredImagePngBytes []byte
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authentication required or invalid credentials
	Object *PreviewFileResponseBody
}

func (p *PreviewFileResponse) GetTwoHundredImageJpegBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImageJpegBytes
}

func (p *PreviewFileResponse) GetTwoHundredImagePngBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImagePngBytes
}

func (p *PreviewFileResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PreviewFileResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PreviewFileResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PreviewFileResponse) GetObject() *PreviewFileResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
