// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type PreviewS3FileRequest struct {
	S3Ref *shared.S3Ref `request:"mediaType=application/json"`
	// height
	H *int64 `queryParam:"style=form,explode=true,name=h"`
	// width
	W *int64 `queryParam:"style=form,explode=true,name=w"`
}

func (p *PreviewS3FileRequest) GetS3Ref() *shared.S3Ref {
	if p == nil {
		return nil
	}
	return p.S3Ref
}

func (p *PreviewS3FileRequest) GetH() *int64 {
	if p == nil {
		return nil
	}
	return p.H
}

func (p *PreviewS3FileRequest) GetW() *int64 {
	if p == nil {
		return nil
	}
	return p.W
}

type PreviewS3FileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PreviewS3FileResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PreviewS3FileResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PreviewS3FileResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
