// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PreviewS3FileGetRequest struct {
	// The S3 bucket name
	Bucket string `queryParam:"style=form,explode=true,name=bucket"`
	// Desired height in pixels
	H *int64 `queryParam:"style=form,explode=true,name=h"`
	// The S3 object key
	Key string `queryParam:"style=form,explode=true,name=key"`
	// Desired width in pixels
	W *int64 `queryParam:"style=form,explode=true,name=w"`
}

func (p *PreviewS3FileGetRequest) GetBucket() string {
	if p == nil {
		return ""
	}
	return p.Bucket
}

func (p *PreviewS3FileGetRequest) GetH() *int64 {
	if p == nil {
		return nil
	}
	return p.H
}

func (p *PreviewS3FileGetRequest) GetKey() string {
	if p == nil {
		return ""
	}
	return p.Key
}

func (p *PreviewS3FileGetRequest) GetW() *int64 {
	if p == nil {
		return nil
	}
	return p.W
}

// #region class-body-previews3filegetrequest
// #endregion class-body-previews3filegetrequest

// PreviewS3FileGetResponseBody - A generic error returned by the API
type PreviewS3FileGetResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (p *PreviewS3FileGetResponseBody) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PreviewS3FileGetResponseBody) GetStatus() *int64 {
	if p == nil {
		return nil
	}
	return p.Status
}

// #region class-body-previews3filegetresponsebody
// #endregion class-body-previews3filegetresponsebody

type PreviewS3FileGetResponse struct {
	// Generated thumbnail image
	TwoHundredImageJpegBytes []byte
	// Generated thumbnail image
	TwoHundredImagePngBytes []byte
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *PreviewS3FileGetResponseBody
}

func (p *PreviewS3FileGetResponse) GetTwoHundredImageJpegBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImageJpegBytes
}

func (p *PreviewS3FileGetResponse) GetTwoHundredImagePngBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImagePngBytes
}

func (p *PreviewS3FileGetResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PreviewS3FileGetResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PreviewS3FileGetResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PreviewS3FileGetResponse) GetObject() *PreviewS3FileGetResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}

// #region class-body-previews3filegetresponse
// #endregion class-body-previews3filegetresponse
