// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type PreviewPublicFileRequest struct {
	// Desired height in pixels
	H *int64 `queryParam:"style=form,explode=true,name=h"`
	// The UUID of the public file entity
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Organization ID that owns the file
	OrgID *string `queryParam:"style=form,explode=true,name=org_id"`
	// Index of the file version to preview (0 = latest)
	Version *int64 `default:"0" queryParam:"style=form,explode=true,name=version"`
	// Desired width in pixels
	W *int64 `queryParam:"style=form,explode=true,name=w"`
}

func (p PreviewPublicFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PreviewPublicFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PreviewPublicFileRequest) GetH() *int64 {
	if p == nil {
		return nil
	}
	return p.H
}

func (p *PreviewPublicFileRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PreviewPublicFileRequest) GetOrgID() *string {
	if p == nil {
		return nil
	}
	return p.OrgID
}

func (p *PreviewPublicFileRequest) GetVersion() *int64 {
	if p == nil {
		return nil
	}
	return p.Version
}

func (p *PreviewPublicFileRequest) GetW() *int64 {
	if p == nil {
		return nil
	}
	return p.W
}

// PreviewPublicFileResponseBody - A generic error returned by the API
type PreviewPublicFileResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (p *PreviewPublicFileResponseBody) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PreviewPublicFileResponseBody) GetStatus() *int64 {
	if p == nil {
		return nil
	}
	return p.Status
}

type PreviewPublicFileResponse struct {
	// Generated thumbnail image for a public file
	TwoHundredImageJpegBytes []byte
	// Generated thumbnail image for a public file
	TwoHundredImagePngBytes []byte
	// HTTP response content type for this operation
	ContentType string
	// File is not public
	ErrorObject *shared.ErrorObject
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *PreviewPublicFileResponseBody
}

func (p *PreviewPublicFileResponse) GetTwoHundredImageJpegBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImageJpegBytes
}

func (p *PreviewPublicFileResponse) GetTwoHundredImagePngBytes() []byte {
	if p == nil {
		return nil
	}
	return p.TwoHundredImagePngBytes
}

func (p *PreviewPublicFileResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PreviewPublicFileResponse) GetErrorObject() *shared.ErrorObject {
	if p == nil {
		return nil
	}
	return p.ErrorObject
}

func (p *PreviewPublicFileResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PreviewPublicFileResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PreviewPublicFileResponse) GetObject() *PreviewPublicFileResponseBody {
	if p == nil {
		return nil
	}
	return p.Object
}
