// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type SaveFileRequest struct {
	SaveFilePayload *shared.SaveFilePayload `request:"mediaType=application/json"`
	// Activity to include in event feed
	ActivityID *string `queryParam:"style=form,explode=true,name=activity_id"`
	// Don't wait for updated entity to become available in Search API. Useful for large migrations
	Async *bool `default:"false" queryParam:"style=form,explode=true,name=async"`
	// When true, only adds a new file version and updates the entity's
	// s3ref to point to the new version, without overwriting the entity's
	// existing top-level metadata. The entity's filename, type, and other
	// fields are preserved as-is. The new version entry in the versions
	// array will contain the file-level metadata (filename, mime_type, etc).
	// Only applies when updating an existing entity (_id or file_entity_id is set).
	//
	VersionOnly *bool `default:"false" queryParam:"style=form,explode=true,name=version_only"`
}

func (s SaveFileRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SaveFileRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SaveFileRequest) GetSaveFilePayload() *shared.SaveFilePayload {
	if s == nil {
		return nil
	}
	return s.SaveFilePayload
}

func (s *SaveFileRequest) GetActivityID() *string {
	if s == nil {
		return nil
	}
	return s.ActivityID
}

func (s *SaveFileRequest) GetAsync() *bool {
	if s == nil {
		return nil
	}
	return s.Async
}

func (s *SaveFileRequest) GetVersionOnly() *bool {
	if s == nil {
		return nil
	}
	return s.VersionOnly
}

// SaveFileResponseBody - A generic error returned by the API
type SaveFileResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (s *SaveFileResponseBody) GetError() *string {
	if s == nil {
		return nil
	}
	return s.Error
}

func (s *SaveFileResponseBody) GetStatus() *int64 {
	if s == nil {
		return nil
	}
	return s.Status
}

type SaveFileResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Created File Entity
	FileEntity *shared.FileEntity
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *SaveFileResponseBody
}

func (s *SaveFileResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *SaveFileResponse) GetFileEntity() *shared.FileEntity {
	if s == nil {
		return nil
	}
	return s.FileEntity
}

func (s *SaveFileResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SaveFileResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *SaveFileResponse) GetObject() *SaveFileResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
