// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type UpdateUserSchemaFileCollectionRequest struct {
	FileCollectionAttributes shared.FileCollectionAttributes `request:"mediaType=application/json"`
	// The slug identifier for the collection
	CollectionSlug string `pathParam:"style=simple,explode=false,name=collectionSlug"`
	// The schema slug (e.g., order, opportunity)
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (u *UpdateUserSchemaFileCollectionRequest) GetFileCollectionAttributes() shared.FileCollectionAttributes {
	if u == nil {
		return shared.FileCollectionAttributes{}
	}
	return u.FileCollectionAttributes
}

func (u *UpdateUserSchemaFileCollectionRequest) GetCollectionSlug() string {
	if u == nil {
		return ""
	}
	return u.CollectionSlug
}

func (u *UpdateUserSchemaFileCollectionRequest) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

// UpdateUserSchemaFileCollectionResponseBody - A generic error returned by the API
type UpdateUserSchemaFileCollectionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (u *UpdateUserSchemaFileCollectionResponseBody) GetError() *string {
	if u == nil {
		return nil
	}
	return u.Error
}

func (u *UpdateUserSchemaFileCollectionResponseBody) GetStatus() *int64 {
	if u == nil {
		return nil
	}
	return u.Status
}

type UpdateUserSchemaFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File collection updated successfully
	FileCollectionItem *shared.FileCollectionItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *UpdateUserSchemaFileCollectionResponseBody
}

func (u *UpdateUserSchemaFileCollectionResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateUserSchemaFileCollectionResponse) GetFileCollectionItem() *shared.FileCollectionItem {
	if u == nil {
		return nil
	}
	return u.FileCollectionItem
}

func (u *UpdateUserSchemaFileCollectionResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateUserSchemaFileCollectionResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateUserSchemaFileCollectionResponse) GetObject() *UpdateUserSchemaFileCollectionResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
