// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type UpdateFileCollectionRequest struct {
	FileCollectionAttributes shared.FileCollectionAttributes `request:"mediaType=application/json"`
	// The slug identifier for the collection
	CollectionSlug string `pathParam:"style=simple,explode=false,name=collectionSlug"`
	// Entity id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UpdateFileCollectionRequest) GetFileCollectionAttributes() shared.FileCollectionAttributes {
	if o == nil {
		return shared.FileCollectionAttributes{}
	}
	return o.FileCollectionAttributes
}

func (o *UpdateFileCollectionRequest) GetCollectionSlug() string {
	if o == nil {
		return ""
	}
	return o.CollectionSlug
}

func (o *UpdateFileCollectionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// UpdateFileCollectionResponseBody - A generic error returned by the API
type UpdateFileCollectionResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (o *UpdateFileCollectionResponseBody) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *UpdateFileCollectionResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type UpdateFileCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// File collection updated successfully
	FileCollectionItem *shared.FileCollectionItem
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The requested resource was not found
	Object *UpdateFileCollectionResponseBody
}

func (o *UpdateFileCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateFileCollectionResponse) GetFileCollectionItem() *shared.FileCollectionItem {
	if o == nil {
		return nil
	}
	return o.FileCollectionItem
}

func (o *UpdateFileCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateFileCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateFileCollectionResponse) GetObject() *UpdateFileCollectionResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
