// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UploadFilePublicS3ref struct {
	Bucket string `json:"bucket"`
	Key    string `json:"key"`
}

func (u *UploadFilePublicS3ref) GetBucket() string {
	if u == nil {
		return ""
	}
	return u.Bucket
}

func (u *UploadFilePublicS3ref) GetKey() string {
	if u == nil {
		return ""
	}
	return u.Key
}

// UploadFilePublicResponseBody - Pre-signed URL for POST / PUT upload
type UploadFilePublicResponseBody struct {
	Error     *string                `json:"error,omitempty"`
	S3ref     *UploadFilePublicS3ref `json:"s3ref,omitempty"`
	UploadURL *string                `json:"upload_url,omitempty"`
}

func (u *UploadFilePublicResponseBody) GetError() *string {
	if u == nil {
		return nil
	}
	return u.Error
}

func (u *UploadFilePublicResponseBody) GetS3ref() *UploadFilePublicS3ref {
	if u == nil {
		return nil
	}
	return u.S3ref
}

func (u *UploadFilePublicResponseBody) GetUploadURL() *string {
	if u == nil {
		return nil
	}
	return u.UploadURL
}

type UploadFilePublicResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Pre-signed URL for POST / PUT upload
	Object *UploadFilePublicResponseBody
}

func (u *UploadFilePublicResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UploadFilePublicResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UploadFilePublicResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UploadFilePublicResponse) GetObject() *UploadFilePublicResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
