// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"net/http"
)

type UploadFileV2Request struct {
	UploadFilePayload *shared.UploadFilePayload `request:"mediaType=application/json"`
	// Use this parameter when uploading a file directly to an existing file entity.
	//
	// Note: still requires calling saveFileV2 to save the file permanently.
	//
	FileEntityID *string `queryParam:"style=form,explode=true,name=file_entity_id"`
}

func (u *UploadFileV2Request) GetUploadFilePayload() *shared.UploadFilePayload {
	if u == nil {
		return nil
	}
	return u.UploadFilePayload
}

func (u *UploadFileV2Request) GetFileEntityID() *string {
	if u == nil {
		return nil
	}
	return u.FileEntityID
}

// #region class-body-uploadfilev2request
// #endregion class-body-uploadfilev2request

// UploadFileV2ResponseBody - A generic error returned by the API
type UploadFileV2ResponseBody struct {
	// The error message
	Error *string `json:"error,omitempty"`
	// The HTTP status code of the error
	Status *int64 `json:"status,omitempty"`
}

func (u *UploadFileV2ResponseBody) GetError() *string {
	if u == nil {
		return nil
	}
	return u.Error
}

func (u *UploadFileV2ResponseBody) GetStatus() *int64 {
	if u == nil {
		return nil
	}
	return u.Status
}

// #region class-body-uploadfilev2responsebody
// #endregion class-body-uploadfilev2responsebody

type UploadFileV2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Pre-signed URL for POST / PUT upload
	FileUpload *shared.FileUpload
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request parameters or payload
	Object *UploadFileV2ResponseBody
}

func (u *UploadFileV2Response) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UploadFileV2Response) GetFileUpload() *shared.FileUpload {
	if u == nil {
		return nil
	}
	return u.FileUpload
}

func (u *UploadFileV2Response) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UploadFileV2Response) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UploadFileV2Response) GetObject() *UploadFileV2ResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}

// #region class-body-uploadfilev2response
// #endregion class-body-uploadfilev2response
