// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DownloadFilesPayload struct {
	ID string `json:"id"`
	// File version
	Version *int64 `json:"version,omitempty"`
}

func (o *DownloadFilesPayload) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DownloadFilesPayload) GetVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.Version
}
