// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

type AccessControl string

const (
	AccessControlPrivate    AccessControl = "private"
	AccessControlPublicRead AccessControl = "public-read"
)

func (e AccessControl) ToPointer() *AccessControl {
	return &e
}
func (e *AccessControl) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public-read":
		*e = AccessControl(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessControl: %v", v)
	}
}

// BatchSaveFileVersionPayload - Payload for batch version save. Only s3ref payloads are supported.
type BatchSaveFileVersionPayload struct {
	ID            *string        `json:"_id,omitempty"`
	AccessControl *AccessControl `default:"private" json:"access_control"`
	// Deprecated, use _id instead
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	FileEntityID *string `json:"file_entity_id,omitempty"`
	Filename     *string `json:"filename,omitempty"`
	MimeType     *string `json:"mime_type,omitempty"`
	S3ref        S3Ref   `json:"s3ref"`
}

func (b BatchSaveFileVersionPayload) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BatchSaveFileVersionPayload) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BatchSaveFileVersionPayload) GetID() *string {
	if b == nil {
		return nil
	}
	return b.ID
}

func (b *BatchSaveFileVersionPayload) GetAccessControl() *AccessControl {
	if b == nil {
		return nil
	}
	return b.AccessControl
}

func (b *BatchSaveFileVersionPayload) GetFileEntityID() *string {
	if b == nil {
		return nil
	}
	return b.FileEntityID
}

func (b *BatchSaveFileVersionPayload) GetFilename() *string {
	if b == nil {
		return nil
	}
	return b.Filename
}

func (b *BatchSaveFileVersionPayload) GetMimeType() *string {
	if b == nil {
		return nil
	}
	return b.MimeType
}

func (b *BatchSaveFileVersionPayload) GetS3ref() S3Ref {
	if b == nil {
		return S3Ref{}
	}
	return b.S3ref
}
