// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

// CreateZipJobPayloadEntityQuery - Entity search query used to resolve files to include in the ZIP
type CreateZipJobPayloadEntityQuery struct {
	// Lucene-style search query (same syntax as entity search)
	Q string `json:"q"`
	// Sort expression forwarded to the entity search
	Sort *string `json:"sort,omitempty"`
}

func (c CreateZipJobPayloadEntityQuery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateZipJobPayloadEntityQuery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateZipJobPayloadEntityQuery) GetQ() string {
	if c == nil {
		return ""
	}
	return c.Q
}

func (c *CreateZipJobPayloadEntityQuery) GetSort() *string {
	if c == nil {
		return nil
	}
	return c.Sort
}

type Two struct {
	// Entity search query used to resolve files to include in the ZIP
	EntityQuery CreateZipJobPayloadEntityQuery `json:"entity_query"`
	// List of file entity IDs to include in the ZIP
	FileEntityIds []string `json:"file_entity_ids,omitempty"`
	// Send email notification when ZIP is ready
	NotifyEmail *bool `default:"true" json:"notify_email"`
	// Name of the generated ZIP file
	ZipFilename *string `default:"Files.zip" json:"zip_filename"`
}

func (t Two) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Two) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Two) GetEntityQuery() CreateZipJobPayloadEntityQuery {
	if t == nil {
		return CreateZipJobPayloadEntityQuery{}
	}
	return t.EntityQuery
}

func (t *Two) GetFileEntityIds() []string {
	if t == nil {
		return nil
	}
	return t.FileEntityIds
}

func (t *Two) GetNotifyEmail() *bool {
	if t == nil {
		return nil
	}
	return t.NotifyEmail
}

func (t *Two) GetZipFilename() *string {
	if t == nil {
		return nil
	}
	return t.ZipFilename
}

// EntityQuery - Entity search query used to resolve files to include in the ZIP
type EntityQuery struct {
	// Lucene-style search query (same syntax as entity search)
	Q string `json:"q"`
	// Sort expression forwarded to the entity search
	Sort *string `json:"sort,omitempty"`
}

func (e EntityQuery) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EntityQuery) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EntityQuery) GetQ() string {
	if e == nil {
		return ""
	}
	return e.Q
}

func (e *EntityQuery) GetSort() *string {
	if e == nil {
		return nil
	}
	return e.Sort
}

type One struct {
	// Entity search query used to resolve files to include in the ZIP
	EntityQuery *EntityQuery `json:"entity_query,omitempty"`
	// List of file entity IDs to include in the ZIP
	FileEntityIds []string `json:"file_entity_ids"`
	// Send email notification when ZIP is ready
	NotifyEmail *bool `default:"true" json:"notify_email"`
	// Name of the generated ZIP file
	ZipFilename *string `default:"Files.zip" json:"zip_filename"`
}

func (o One) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *One) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *One) GetEntityQuery() *EntityQuery {
	if o == nil {
		return nil
	}
	return o.EntityQuery
}

func (o *One) GetFileEntityIds() []string {
	if o == nil {
		return []string{}
	}
	return o.FileEntityIds
}

func (o *One) GetNotifyEmail() *bool {
	if o == nil {
		return nil
	}
	return o.NotifyEmail
}

func (o *One) GetZipFilename() *string {
	if o == nil {
		return nil
	}
	return o.ZipFilename
}

type CreateZipJobPayloadType string

const (
	CreateZipJobPayloadTypeOne CreateZipJobPayloadType = "1"
	CreateZipJobPayloadTypeTwo CreateZipJobPayloadType = "2"
)

// CreateZipJobPayload - Request payload to create a ZIP job for bulk file download.
// Provide either an explicit list of `file_entity_ids` (up to 1000) or an
// `entity_query` that resolves to file entities (up to 10000).
type CreateZipJobPayload struct {
	One *One `queryParam:"inline" union:"member"`
	Two *Two `queryParam:"inline" union:"member"`

	Type CreateZipJobPayloadType
}

func CreateCreateZipJobPayloadOne(one One) CreateZipJobPayload {
	typ := CreateZipJobPayloadTypeOne

	return CreateZipJobPayload{
		One:  &one,
		Type: typ,
	}
}

func CreateCreateZipJobPayloadTwo(two Two) CreateZipJobPayload {
	typ := CreateZipJobPayloadTypeTwo

	return CreateZipJobPayload{
		Two:  &two,
		Type: typ,
	}
}

func (u *CreateZipJobPayload) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var one One = One{}
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateZipJobPayloadTypeOne,
			Value: &one,
		})
	}

	var two Two = Two{}
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  CreateZipJobPayloadTypeTwo,
			Value: &two,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateZipJobPayload", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateZipJobPayload", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(CreateZipJobPayloadType)
	switch best.Type {
	case CreateZipJobPayloadTypeOne:
		u.One = best.Value.(*One)
		return nil
	case CreateZipJobPayloadTypeTwo:
		u.Two = best.Value.(*Two)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateZipJobPayload", string(data))
}

func (u CreateZipJobPayload) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	return nil, errors.New("could not marshal union type CreateZipJobPayload: all fields are null")
}
