// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CustomDownloadURLAuth - Authorization mode for the custom_download_url. `presigned` (the default) uses an HMAC-signed URL; `token` authorizes the download via the caller's bearer token, matched against the exact stored custom_download_url. In token mode the File API returns the unsigned custom_download_url (no expires_at/signature query params) so the stored url matches exactly.
type CustomDownloadURLAuth string

const (
	CustomDownloadURLAuthPresigned CustomDownloadURLAuth = "presigned"
	CustomDownloadURLAuthToken     CustomDownloadURLAuth = "token"
)

func (e CustomDownloadURLAuth) ToPointer() *CustomDownloadURLAuth {
	return &e
}
func (e *CustomDownloadURLAuth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "presigned":
		fallthrough
	case "token":
		*e = CustomDownloadURLAuth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomDownloadURLAuth: %v", v)
	}
}
