// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

type FileTextUnsupportedSchemas struct {
	// Availability of the plain-text representation for a file entity.
	Status     FileTextStatus `json:"status"`
	Text       *string        `json:"text,omitempty"`
	TotalChars *int64         `json:"total_chars,omitempty"`
	Truncated  *bool          `json:"truncated,omitempty"`
}

func (f FileTextUnsupportedSchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileTextUnsupportedSchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileTextUnsupportedSchemas) GetStatus() FileTextStatus {
	if f == nil {
		return FileTextStatus("")
	}
	return f.Status
}

func (f *FileTextUnsupportedSchemas) GetText() *string {
	if f == nil {
		return nil
	}
	return f.Text
}

func (f *FileTextUnsupportedSchemas) GetTotalChars() *int64 {
	if f == nil {
		return nil
	}
	return f.TotalChars
}

func (f *FileTextUnsupportedSchemas) GetTruncated() *bool {
	if f == nil {
		return nil
	}
	return f.Truncated
}

type Schemas struct {
	// Availability of the plain-text representation for a file entity.
	Status     FileTextStatus `json:"status"`
	Text       *string        `json:"text,omitempty"`
	TotalChars *int64         `json:"total_chars,omitempty"`
	Truncated  *bool          `json:"truncated,omitempty"`
}

func (s Schemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Schemas) GetStatus() FileTextStatus {
	if s == nil {
		return FileTextStatus("")
	}
	return s.Status
}

func (s *Schemas) GetText() *string {
	if s == nil {
		return nil
	}
	return s.Text
}

func (s *Schemas) GetTotalChars() *int64 {
	if s == nil {
		return nil
	}
	return s.TotalChars
}

func (s *Schemas) GetTruncated() *bool {
	if s == nil {
		return nil
	}
	return s.Truncated
}

type FileTextReadySchemas struct {
	// Availability of the plain-text representation for a file entity.
	Status     FileTextStatus `json:"status"`
	Text       string         `json:"text"`
	TotalChars int64          `json:"total_chars"`
	Truncated  bool           `json:"truncated"`
}

func (f FileTextReadySchemas) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileTextReadySchemas) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileTextReadySchemas) GetStatus() FileTextStatus {
	if f == nil {
		return FileTextStatus("")
	}
	return f.Status
}

func (f *FileTextReadySchemas) GetText() string {
	if f == nil {
		return ""
	}
	return f.Text
}

func (f *FileTextReadySchemas) GetTotalChars() int64 {
	if f == nil {
		return 0
	}
	return f.TotalChars
}

func (f *FileTextReadySchemas) GetTruncated() bool {
	if f == nil {
		return false
	}
	return f.Truncated
}

type FileTextType string

const (
	FileTextTypeFileTextReadySchemas       FileTextType = "FileTextReady_Schemas"
	FileTextTypeSchemas                    FileTextType = "Schemas"
	FileTextTypeFileTextUnsupportedSchemas FileTextType = "FileTextUnsupported_Schemas"
)

type FileText struct {
	FileTextReadySchemas       *FileTextReadySchemas       `queryParam:"inline" union:"member"`
	Schemas                    *Schemas                    `queryParam:"inline" union:"member"`
	FileTextUnsupportedSchemas *FileTextUnsupportedSchemas `queryParam:"inline" union:"member"`

	Type FileTextType
}

func CreateFileTextFileTextReadySchemas(fileTextReadySchemas FileTextReadySchemas) FileText {
	typ := FileTextTypeFileTextReadySchemas

	return FileText{
		FileTextReadySchemas: &fileTextReadySchemas,
		Type:                 typ,
	}
}

func CreateFileTextSchemas(schemas Schemas) FileText {
	typ := FileTextTypeSchemas

	return FileText{
		Schemas: &schemas,
		Type:    typ,
	}
}

func CreateFileTextFileTextUnsupportedSchemas(fileTextUnsupportedSchemas FileTextUnsupportedSchemas) FileText {
	typ := FileTextTypeFileTextUnsupportedSchemas

	return FileText{
		FileTextUnsupportedSchemas: &fileTextUnsupportedSchemas,
		Type:                       typ,
	}
}

func (u *FileText) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var fileTextReadySchemas FileTextReadySchemas = FileTextReadySchemas{}
	if err := utils.UnmarshalJSON(data, &fileTextReadySchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileTextTypeFileTextReadySchemas,
			Value: &fileTextReadySchemas,
		})
	}

	var schemas Schemas = Schemas{}
	if err := utils.UnmarshalJSON(data, &schemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileTextTypeSchemas,
			Value: &schemas,
		})
	}

	var fileTextUnsupportedSchemas FileTextUnsupportedSchemas = FileTextUnsupportedSchemas{}
	if err := utils.UnmarshalJSON(data, &fileTextUnsupportedSchemas, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  FileTextTypeFileTextUnsupportedSchemas,
			Value: &fileTextUnsupportedSchemas,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileText", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileText", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(FileTextType)
	switch best.Type {
	case FileTextTypeFileTextReadySchemas:
		u.FileTextReadySchemas = best.Value.(*FileTextReadySchemas)
		return nil
	case FileTextTypeSchemas:
		u.Schemas = best.Value.(*Schemas)
		return nil
	case FileTextTypeFileTextUnsupportedSchemas:
		u.FileTextUnsupportedSchemas = best.Value.(*FileTextUnsupportedSchemas)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FileText", string(data))
}

func (u FileText) MarshalJSON() ([]byte, error) {
	if u.FileTextReadySchemas != nil {
		return utils.MarshalJSON(u.FileTextReadySchemas, "", true)
	}

	if u.Schemas != nil {
		return utils.MarshalJSON(u.Schemas, "", true)
	}

	if u.FileTextUnsupportedSchemas != nil {
		return utils.MarshalJSON(u.FileTextUnsupportedSchemas, "", true)
	}

	return nil, errors.New("could not marshal union type FileText: all fields are null")
}
