// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
	"time"
)

// FileCollectionItem - A file collection with identifiers and timestamps
type FileCollectionItem struct {
	// Timestamp when the collection was created
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Generated uuid for a file collection
	ID *string `json:"id,omitempty"`
	// Display name of the collection
	Name string `json:"name"`
	// Display order for the collection
	Order *float64 `json:"order,omitempty"`
	// Array of parent collection slugs, empty array if top-level collection. Format depends on collection type:
	// - User collection: `_system_files_collection_{entity_uuid}_{user_id}`
	//   Example: `["_system_files_collection_3fa85f64-5717-4562-b3fc-2c963f66afa6_10234"]`
	// - Global collection: `_system_files_collection_schema_{schema_slug}`
	//   Example: `["_system_files_collection_schema_opportunity"]`
	//
	Parents []string `json:"parents,omitempty"`
	// Full slug for the collection. Format depends on collection type:
	// - User collection: `_system_files_collection_{entity_uuid}_{user_id}:{collection_name}`
	//   Example: `_system_files_collection_3fa85f64-5717-4562-b3fc-2c963f66afa6_10234:documents`
	// - Global collection: `_system_files_collection_schema_{schema_slug}:{collection_name}`
	//   Example: `_system_files_collection_schema_opportunity:templates`
	//
	Slug *string `json:"slug,omitempty"`
	// Whether the collection is starred / favorited
	Starred *bool `json:"starred,omitempty"`
	// Timestamp when the collection was last updated
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

func (f FileCollectionItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileCollectionItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (f *FileCollectionItem) GetCreatedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.CreatedAt
}

func (f *FileCollectionItem) GetID() *string {
	if f == nil {
		return nil
	}
	return f.ID
}

func (f *FileCollectionItem) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FileCollectionItem) GetOrder() *float64 {
	if f == nil {
		return nil
	}
	return f.Order
}

func (f *FileCollectionItem) GetParents() []string {
	if f == nil {
		return nil
	}
	return f.Parents
}

func (f *FileCollectionItem) GetSlug() *string {
	if f == nil {
		return nil
	}
	return f.Slug
}

func (f *FileCollectionItem) GetStarred() *bool {
	if f == nil {
		return nil
	}
	return f.Starred
}

func (f *FileCollectionItem) GetUpdatedAt() *time.Time {
	if f == nil {
		return nil
	}
	return f.UpdatedAt
}
