// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

type FileFolderAttributes struct {
	// Name of the folder
	Name *string `json:"name,omitempty"`
	// Array of parent folder slugs, empty array if top-level folder
	Parents []string `json:"parents,omitempty"`
	// Whether the folder is starred / favorited
	Starred *bool `default:"false" json:"starred"`
}

func (f FileFolderAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileFolderAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FileFolderAttributes) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *FileFolderAttributes) GetParents() []string {
	if f == nil {
		return nil
	}
	return f.Parents
}

func (f *FileFolderAttributes) GetStarred() *bool {
	if f == nil {
		return nil
	}
	return f.Starred
}
