// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

type FileCollectionAttributes struct {
	// Name of the collection
	Name *string `json:"name,omitempty"`
	// Array of parent collection slugs, empty array if top-level collection
	Parents []string `json:"parents,omitempty"`
	// Whether the collection is starred / favorited
	Starred *bool `default:"false" json:"starred"`
}

func (f FileCollectionAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FileCollectionAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *FileCollectionAttributes) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *FileCollectionAttributes) GetParents() []string {
	if o == nil {
		return nil
	}
	return o.Parents
}

func (o *FileCollectionAttributes) GetStarred() *bool {
	if o == nil {
		return nil
	}
	return o.Starred
}
