// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"errors"
	"fmt"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/internal/utils"
)

type SaveFilePayloadType string

const (
	SaveFilePayloadTypeSaveS3FilePayload            SaveFilePayloadType = "SaveS3FilePayload"
	SaveFilePayloadTypeSaveFileFromSourceURLPayload SaveFilePayloadType = "SaveFileFromSourceURLPayload"
	SaveFilePayloadTypeSaveCustomFilePayload        SaveFilePayloadType = "SaveCustomFilePayload"
)

type SaveFilePayload struct {
	SaveS3FilePayload            *SaveS3FilePayload            `queryParam:"inline,name=SaveFilePayload"`
	SaveFileFromSourceURLPayload *SaveFileFromSourceURLPayload `queryParam:"inline,name=SaveFilePayload"`
	SaveCustomFilePayload        *SaveCustomFilePayload        `queryParam:"inline,name=SaveFilePayload"`

	Type SaveFilePayloadType
}

func CreateSaveFilePayloadSaveS3FilePayload(saveS3FilePayload SaveS3FilePayload) SaveFilePayload {
	typ := SaveFilePayloadTypeSaveS3FilePayload

	return SaveFilePayload{
		SaveS3FilePayload: &saveS3FilePayload,
		Type:              typ,
	}
}

func CreateSaveFilePayloadSaveFileFromSourceURLPayload(saveFileFromSourceURLPayload SaveFileFromSourceURLPayload) SaveFilePayload {
	typ := SaveFilePayloadTypeSaveFileFromSourceURLPayload

	return SaveFilePayload{
		SaveFileFromSourceURLPayload: &saveFileFromSourceURLPayload,
		Type:                         typ,
	}
}

func CreateSaveFilePayloadSaveCustomFilePayload(saveCustomFilePayload SaveCustomFilePayload) SaveFilePayload {
	typ := SaveFilePayloadTypeSaveCustomFilePayload

	return SaveFilePayload{
		SaveCustomFilePayload: &saveCustomFilePayload,
		Type:                  typ,
	}
}

func (u *SaveFilePayload) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var saveS3FilePayload SaveS3FilePayload = SaveS3FilePayload{}
	if err := utils.UnmarshalJSON(data, &saveS3FilePayload, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SaveFilePayloadTypeSaveS3FilePayload,
			Value: &saveS3FilePayload,
		})
	}

	var saveFileFromSourceURLPayload SaveFileFromSourceURLPayload = SaveFileFromSourceURLPayload{}
	if err := utils.UnmarshalJSON(data, &saveFileFromSourceURLPayload, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SaveFilePayloadTypeSaveFileFromSourceURLPayload,
			Value: &saveFileFromSourceURLPayload,
		})
	}

	var saveCustomFilePayload SaveCustomFilePayload = SaveCustomFilePayload{}
	if err := utils.UnmarshalJSON(data, &saveCustomFilePayload, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  SaveFilePayloadTypeSaveCustomFilePayload,
			Value: &saveCustomFilePayload,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SaveFilePayload", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestCandidate(candidates)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for SaveFilePayload", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(SaveFilePayloadType)
	switch best.Type {
	case SaveFilePayloadTypeSaveS3FilePayload:
		u.SaveS3FilePayload = best.Value.(*SaveS3FilePayload)
		return nil
	case SaveFilePayloadTypeSaveFileFromSourceURLPayload:
		u.SaveFileFromSourceURLPayload = best.Value.(*SaveFileFromSourceURLPayload)
		return nil
	case SaveFilePayloadTypeSaveCustomFilePayload:
		u.SaveCustomFilePayload = best.Value.(*SaveCustomFilePayload)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for SaveFilePayload", string(data))
}

func (u SaveFilePayload) MarshalJSON() ([]byte, error) {
	if u.SaveS3FilePayload != nil {
		return utils.MarshalJSON(u.SaveS3FilePayload, "", true)
	}

	if u.SaveFileFromSourceURLPayload != nil {
		return utils.MarshalJSON(u.SaveFileFromSourceURLPayload, "", true)
	}

	if u.SaveCustomFilePayload != nil {
		return utils.MarshalJSON(u.SaveCustomFilePayload, "", true)
	}

	return nil, errors.New("could not marshal union type SaveFilePayload: all fields are null")
}
