// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/provider/typeconvert"
	tfTypes "github.com/epilot-dev/terraform-provider-epilot-file/internal/provider/types"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/operations"
	"github.com/epilot-dev/terraform-provider-epilot-file/internal/sdk/models/shared"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *FileResourceModel) RefreshFromSharedFileEntity(ctx context.Context, resp *shared.FileEntity) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.Additional != nil {
			r.Additional = make(map[string]jsontypes.Normalized, len(resp.Additional))
			for key, value := range resp.Additional {
				result, _ := json.Marshal(value)
				r.Additional[key] = jsontypes.NewNormalizedValue(string(result))
			}
		}
		if resp.ACL == nil {
			r.ACL = nil
		} else {
			r.ACL = &tfTypes.BaseEntityACL{}
			r.ACL.Delete = make([]types.String, 0, len(resp.ACL.Delete))
			for _, v := range resp.ACL.Delete {
				r.ACL.Delete = append(r.ACL.Delete, types.StringValue(v))
			}
			r.ACL.Edit = make([]types.String, 0, len(resp.ACL.Edit))
			for _, v := range resp.ACL.Edit {
				r.ACL.Edit = append(r.ACL.Edit, types.StringValue(v))
			}
			r.ACL.View = make([]types.String, 0, len(resp.ACL.View))
			for _, v := range resp.ACL.View {
				r.ACL.View = append(r.ACL.View, types.StringValue(v))
			}
		}
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.ID = types.StringPointerValue(resp.ID)
		r.Manifest = make([]types.String, 0, len(resp.Manifest))
		for _, v := range resp.Manifest {
			r.Manifest = append(r.Manifest, types.StringValue(v))
		}
		r.Org = types.StringPointerValue(resp.Org)
		r.Owners = []tfTypes.BaseEntityOwner{}

		for _, ownersItem := range resp.Owners {
			var owners tfTypes.BaseEntityOwner

			owners.OrgID = types.StringValue(ownersItem.OrgID)
			owners.UserID = types.StringPointerValue(ownersItem.UserID)

			r.Owners = append(r.Owners, owners)
		}
		r.Purpose = make([]types.String, 0, len(resp.Purpose))
		for _, v := range resp.Purpose {
			r.Purpose = append(r.Purpose, types.StringValue(v))
		}
		if resp.Schema != nil {
			r.Schema = types.StringValue(string(*resp.Schema))
		} else {
			r.Schema = types.StringNull()
		}
		r.Tags = make([]types.String, 0, len(resp.Tags))
		for _, v := range resp.Tags {
			r.Tags = append(r.Tags, types.StringValue(v))
		}
		r.Title = types.StringPointerValue(resp.Title)
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
		if resp.AccessControl != nil {
			r.AccessControl = types.StringValue(string(*resp.AccessControl))
		} else {
			r.AccessControl = types.StringNull()
		}
		r.CustomDownloadURL = types.StringPointerValue(resp.CustomDownloadURL)
		r.Filename = types.StringPointerValue(resp.Filename)
		r.MimeType = types.StringPointerValue(resp.MimeType)
		r.PublicURL = types.StringPointerValue(resp.PublicURL)
		r.ReadableSize = types.StringPointerValue(resp.ReadableSize)
		if resp.S3ref == nil {
			r.S3ref = nil
		} else {
			r.S3ref = &tfTypes.FileEntityS3ref{}
			r.S3ref.Bucket = types.StringValue(resp.S3ref.Bucket)
			r.S3ref.Key = types.StringValue(resp.S3ref.Key)
		}
		r.SizeBytes = types.Int64PointerValue(resp.SizeBytes)
		r.SourceURL = types.StringPointerValue(resp.SourceURL)
		if resp.Type != nil {
			r.Type = types.StringValue(string(*resp.Type))
		} else {
			r.Type = types.StringNull()
		}
	}

	return diags
}

func (r *FileResourceModel) ToOperationsDeleteFileRequest(ctx context.Context) (*operations.DeleteFileRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	activityID := new(string)
	if !r.ActivityID.IsUnknown() && !r.ActivityID.IsNull() {
		*activityID = r.ActivityID.ValueString()
	} else {
		activityID = nil
	}
	var id string
	id = r.ID.ValueString()

	purge := new(bool)
	if !r.Purge.IsUnknown() && !r.Purge.IsNull() {
		*purge = r.Purge.ValueBool()
	} else {
		purge = nil
	}
	strict := new(bool)
	if !r.Strict.IsUnknown() && !r.Strict.IsNull() {
		*strict = r.Strict.ValueBool()
	} else {
		strict = nil
	}
	out := operations.DeleteFileRequest{
		ActivityID: activityID,
		ID:         id,
		Purge:      purge,
		Strict:     strict,
	}

	return &out, diags
}

func (r *FileResourceModel) ToOperationsGetFileRequest(ctx context.Context) (*operations.GetFileRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	async := new(bool)
	if !r.Async.IsUnknown() && !r.Async.IsNull() {
		*async = r.Async.ValueBool()
	} else {
		async = nil
	}
	var id string
	id = r.ID.ValueString()

	strict := new(bool)
	if !r.Strict.IsUnknown() && !r.Strict.IsNull() {
		*strict = r.Strict.ValueBool()
	} else {
		strict = nil
	}
	out := operations.GetFileRequest{
		Async:  async,
		ID:     id,
		Strict: strict,
	}

	return &out, diags
}

func (r *FileResourceModel) ToOperationsSaveFileV2Request(ctx context.Context) (*operations.SaveFileV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	fileEntity, fileEntityDiags := r.ToSharedFileEntityInput(ctx)
	diags.Append(fileEntityDiags...)

	if diags.HasError() {
		return nil, diags
	}

	activityID := new(string)
	if !r.ActivityID.IsUnknown() && !r.ActivityID.IsNull() {
		*activityID = r.ActivityID.ValueString()
	} else {
		activityID = nil
	}
	async := new(bool)
	if !r.Async.IsUnknown() && !r.Async.IsNull() {
		*async = r.Async.ValueBool()
	} else {
		async = nil
	}
	deleteTempFile := new(bool)
	if !r.DeleteTempFile.IsUnknown() && !r.DeleteTempFile.IsNull() {
		*deleteTempFile = r.DeleteTempFile.ValueBool()
	} else {
		deleteTempFile = nil
	}
	fillActivity := new(bool)
	if !r.FillActivity.IsUnknown() && !r.FillActivity.IsNull() {
		*fillActivity = r.FillActivity.ValueBool()
	} else {
		fillActivity = nil
	}
	strict := new(bool)
	if !r.Strict.IsUnknown() && !r.Strict.IsNull() {
		*strict = r.Strict.ValueBool()
	} else {
		strict = nil
	}
	out := operations.SaveFileV2Request{
		FileEntity:     fileEntity,
		ActivityID:     activityID,
		Async:          async,
		DeleteTempFile: deleteTempFile,
		FillActivity:   fillActivity,
		Strict:         strict,
	}

	return &out, diags
}

func (r *FileResourceModel) ToSharedFileEntityInput(ctx context.Context) (*shared.FileEntityInput, diag.Diagnostics) {
	var diags diag.Diagnostics

	additional := make(map[string]interface{})
	for additionalKey, additionalValue := range r.Additional {
		var additionalInst interface{}
		_ = json.Unmarshal([]byte(additionalValue.ValueString()), &additionalInst)
		additional[additionalKey] = additionalInst
	}
	var acl *shared.BaseEntityACL
	if r.ACL != nil {
		delete := make([]string, 0, len(r.ACL.Delete))
		for _, deleteItem := range r.ACL.Delete {
			delete = append(delete, deleteItem.ValueString())
		}
		edit := make([]string, 0, len(r.ACL.Edit))
		for _, editItem := range r.ACL.Edit {
			edit = append(edit, editItem.ValueString())
		}
		view := make([]string, 0, len(r.ACL.View))
		for _, viewItem := range r.ACL.View {
			view = append(view, viewItem.ValueString())
		}
		acl = &shared.BaseEntityACL{
			Delete: delete,
			Edit:   edit,
			View:   view,
		}
	}
	id := new(string)
	if !r.ID.IsUnknown() && !r.ID.IsNull() {
		*id = r.ID.ValueString()
	} else {
		id = nil
	}
	manifest := make([]string, 0, len(r.Manifest))
	for _, manifestItem := range r.Manifest {
		manifest = append(manifest, manifestItem.ValueString())
	}
	purpose := make([]string, 0, len(r.Purpose))
	for _, purposeItem := range r.Purpose {
		purpose = append(purpose, purposeItem.ValueString())
	}
	tags := make([]string, 0, len(r.Tags))
	for _, tagsItem := range r.Tags {
		tags = append(tags, tagsItem.ValueString())
	}
	title := new(string)
	if !r.Title.IsUnknown() && !r.Title.IsNull() {
		*title = r.Title.ValueString()
	} else {
		title = nil
	}
	accessControl := new(shared.AccessControl)
	if !r.AccessControl.IsUnknown() && !r.AccessControl.IsNull() {
		*accessControl = shared.AccessControl(r.AccessControl.ValueString())
	} else {
		accessControl = nil
	}
	customDownloadURL := new(string)
	if !r.CustomDownloadURL.IsUnknown() && !r.CustomDownloadURL.IsNull() {
		*customDownloadURL = r.CustomDownloadURL.ValueString()
	} else {
		customDownloadURL = nil
	}
	filename := new(string)
	if !r.Filename.IsUnknown() && !r.Filename.IsNull() {
		*filename = r.Filename.ValueString()
	} else {
		filename = nil
	}
	mimeType := new(string)
	if !r.MimeType.IsUnknown() && !r.MimeType.IsNull() {
		*mimeType = r.MimeType.ValueString()
	} else {
		mimeType = nil
	}
	var s3ref *shared.FileEntityS3ref
	if r.S3ref != nil {
		var bucket string
		bucket = r.S3ref.Bucket.ValueString()

		var key string
		key = r.S3ref.Key.ValueString()

		s3ref = &shared.FileEntityS3ref{
			Bucket: bucket,
			Key:    key,
		}
	}
	sourceURL := new(string)
	if !r.SourceURL.IsUnknown() && !r.SourceURL.IsNull() {
		*sourceURL = r.SourceURL.ValueString()
	} else {
		sourceURL = nil
	}
	typeVar := new(shared.FileType)
	if !r.Type.IsUnknown() && !r.Type.IsNull() {
		*typeVar = shared.FileType(r.Type.ValueString())
	} else {
		typeVar = nil
	}
	out := shared.FileEntityInput{
		Additional:        additional,
		ACL:               acl,
		ID:                id,
		Manifest:          manifest,
		Purpose:           purpose,
		Tags:              tags,
		Title:             title,
		AccessControl:     accessControl,
		CustomDownloadURL: customDownloadURL,
		Filename:          filename,
		MimeType:          mimeType,
		S3ref:             s3ref,
		SourceURL:         sourceURL,
		Type:              typeVar,
	}

	return &out, diags
}
